
name: run-maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    steps:
    - name: GitHub Action for Maven
      uses: LucaFeger/action-maven-cli@1.1.0
